### ISSUE TITLE
Metainfo release date seems wrong

### ISSUE THREAD

**Issue by bragefuglseth** [BuonHobo/KatharaGUI#1]
The first commits to this repo were made weeks ago, yet the metainfo file shows the first and current release of the app as having been done in 2023.

**Comment by buonhobo** [comment]
You're right, thanks for reporting!

As soon as I get some free time (hopefully during the weekend) I'll fix up the metainfo file and try to follow the guidelines specified in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/

**Comment by buonhobo** [comment]
Committed, should be on flathub shortly
